services:
  - type: web
    name: java-doc-searcher
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_ONLINE
        value: "true"
